# Generated by Django 6.0.4 on 2026-04-17 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_alter_place_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='place',
            unique_together={('project', 'external_id')},
        ),
    ]
